spring:
  profiles:
    active: dev
  application:
    name: E-commerce Platform

  datasource:
    url: ${ENVIRONMENT_VARIABLE_NAME:default_value}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: "REDIS_PASSWORD"
      repositories:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:YOUR_USERNAME_HERE}
    password: ${MAIL_PASSWORD:YOUR_PASSWORD_HERE}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /maitraStore

security:
  jwt:
    secret-key: "SECRET_KEY_FOR_JWT_SIGNING"

razorpay:
  key-id: "YOUR_TEST_KEY"
  key-secret: "YOUR_TEST_SECRET"

logging:
  level:
    root: INFO
    com.DhrubaStudio.E_commercePlatform: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.web: TRACE
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"